/**
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.annot.desc.annotation;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see eu.jgen.notes.annot.desc.annotation.AnnotationFactory
 * @model kind="package"
 * @generated
 */
public interface AnnotationPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "annotation";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.jgen.eu/notes/annot/desc/Annotation";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "annotation";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AnnotationPackage eINSTANCE = eu.jgen.notes.annot.desc.annotation.impl.AnnotationPackageImpl.init();

  /**
   * The meta object id for the '{@link eu.jgen.notes.annot.desc.annotation.impl.MetadataImpl <em>Metadata</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eu.jgen.notes.annot.desc.annotation.impl.MetadataImpl
   * @see eu.jgen.notes.annot.desc.annotation.impl.AnnotationPackageImpl#getMetadata()
   * @generated
   */
  int METADATA = 0;

  /**
   * The feature id for the '<em><b>Import Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METADATA__IMPORT_SECTION = 0;

  /**
   * The feature id for the '<em><b>Annotations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METADATA__ANNOTATIONS = 1;

  /**
   * The number of structural features of the '<em>Metadata</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METADATA_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link eu.jgen.notes.annot.desc.annotation.Metadata <em>Metadata</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metadata</em>'.
   * @see eu.jgen.notes.annot.desc.annotation.Metadata
   * @generated
   */
  EClass getMetadata();

  /**
   * Returns the meta object for the containment reference '{@link eu.jgen.notes.annot.desc.annotation.Metadata#getImportSection <em>Import Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Import Section</em>'.
   * @see eu.jgen.notes.annot.desc.annotation.Metadata#getImportSection()
   * @see #getMetadata()
   * @generated
   */
  EReference getMetadata_ImportSection();

  /**
   * Returns the meta object for the containment reference list '{@link eu.jgen.notes.annot.desc.annotation.Metadata#getAnnotations <em>Annotations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Annotations</em>'.
   * @see eu.jgen.notes.annot.desc.annotation.Metadata#getAnnotations()
   * @see #getMetadata()
   * @generated
   */
  EReference getMetadata_Annotations();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AnnotationFactory getAnnotationFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link eu.jgen.notes.annot.desc.annotation.impl.MetadataImpl <em>Metadata</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eu.jgen.notes.annot.desc.annotation.impl.MetadataImpl
     * @see eu.jgen.notes.annot.desc.annotation.impl.AnnotationPackageImpl#getMetadata()
     * @generated
     */
    EClass METADATA = eINSTANCE.getMetadata();

    /**
     * The meta object literal for the '<em><b>Import Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METADATA__IMPORT_SECTION = eINSTANCE.getMetadata_ImportSection();

    /**
     * The meta object literal for the '<em><b>Annotations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METADATA__ANNOTATIONS = eINSTANCE.getMetadata_Annotations();

  }

} //AnnotationPackage
