/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.annot.processor.tests.sample

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import eu.jgen.notes.annot.desc.annotation.Metadata
import eu.jgen.notes.annot.desc.tests.AnnotationInjectorProvider

@RunWith(XtextRunner) 
@InjectWith(AnnotationInjectorProvider)
class AnnotationParsingTest { 
	@Inject
	ParseHelper<Metadata> parseHelper 
		@Inject extension ParseHelper<Metadata>
		@Inject extension ValidationTestHelper
	
	@Test   
 	def void loadModel() {
		''' 
		#meta{
		import eu.jgen.notes.annot.processor.tests.sample.Author;
		import eu.jgen.notes.annot.processor.tests.sample.Function;
		@Author (name="John",date="2017-01-01",version="1.0")
		@Function (modname="COSTAM")
		}		'''.parse.assertNoErrors
	}
}
