/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.annot.desc.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import eu.jgen.notes.annot.desc.custom.XtextEditorCustom

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class AnnotationUiModule extends AbstractAnnotationUiModule {
	
	override bindXtextEditor() {
		//super.bindXtextEditor()
		XtextEditorCustom
	}
	
}
