/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.annot.desc.ui;

import com.google.inject.Injector;
import eu.jgen.notes.annot.desc.ui.internal.DescActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AnnotationExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DescActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DescActivator.getInstance().getInjector(DescActivator.EU_JGEN_NOTES_ANNOT_DESC_ANNOTATION);
	}
	
}
