/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.annot.desc.ui.tests;

import com.google.inject.Injector;
import eu.jgen.notes.annot.desc.ui.internal.DescActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AnnotationUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DescActivator.getInstance().getInjector("eu.jgen.notes.annot.desc.Annotation");
	}

}
