/**
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.annot.processor.tests.two;

import com.google.inject.Inject;
import eu.jgen.notes.annot.desc.annotation.Metadata;
import eu.jgen.notes.annot.desc.tests.AnnotationInjectorProvider;
import eu.jgen.notes.annot.processor.impl.MessageKind;
import eu.jgen.notes.annot.processor.impl.MessagerImpl;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(AnnotationInjectorProvider.class)
@SuppressWarnings("all")
public class MessangerParsingTest {
  @Inject
  private ParseHelper<Metadata> parseHelper;
  
  @Inject
  @Extension
  private ParseHelper<Metadata> _parseHelper;
  
  @Inject
  @Extension
  private ValidationTestHelper _validationTestHelper;
  
  @Test
  public void loadModel() {
    new MessagerImpl().printMessage(MessageKind.INFO, "Hello");
  }
}
