/**
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.annot.processor.tests.two;

import com.ca.gen.jmmi.schema.ObjTypeCode;
import com.ca.gen.jmmi.schema.ObjTypeHelper;
import com.google.inject.Inject;
import eu.jgen.notes.annot.desc.annotation.Metadata;
import eu.jgen.notes.annot.desc.tests.AnnotationInjectorProvider;
import eu.jgen.notes.annot.processor.impl.AnnotationWorker;
import eu.jgen.notes.annot.processor.tests.sample.ProcessorImpl;
import eu.jgen.notes.automation.wrapper.JGenEncyclopedia;
import eu.jgen.notes.automation.wrapper.JGenFactory;
import eu.jgen.notes.automation.wrapper.JGenModel;
import eu.jgen.notes.automation.wrapper.JGenObject;
import org.eclipse.xtext.resource.XtextResourceSet;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(AnnotationInjectorProvider.class)
@SuppressWarnings("all")
public class ProcessorTest {
  private static JGenEncyclopedia ency;
  
  private static JGenModel genModel;
  
  @Inject
  private ParseHelper<Metadata> parseHelper;
  
  @Inject
  @Extension
  private ParseHelper<Metadata> _parseHelper;
  
  @Inject
  @Extension
  private ValidationTestHelper _validationTestHelper;
  
  @Inject
  private XtextResourceSet resourceSet;
  
  @Inject
  private AnnotationWorker worker;
  
  @Test
  public void loadModel() {
    JGenFactory factory = JGenFactory.eINSTANCE;
    ProcessorTest.ency = factory.createEncyclopedia();
    ProcessorTest.ency.connect();
    ProcessorTest.genModel = ProcessorTest.ency.findModels()[0];
    JGenObject[] objects = ProcessorTest.genModel.findTypeObjects(ObjTypeHelper.getCode(ObjTypeCode.ACBLKBSD));
    ProcessorImpl _processorImpl = new ProcessorImpl();
    this.worker.initProcessor(_processorImpl).setSources(objects).activate();
  }
}
