/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.annot.desc


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AnnotationStandaloneSetup extends AnnotationStandaloneSetupGenerated {

	def static void doSetup() {
		new AnnotationStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
