/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.annot.desc.parser.antlr;

import com.google.inject.Inject;
import eu.jgen.notes.annot.desc.parser.antlr.internal.InternalAnnotationParser;
import eu.jgen.notes.annot.desc.services.AnnotationGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AnnotationParser extends AbstractAntlrParser {

	@Inject
	private AnnotationGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAnnotationParser createParser(XtextTokenStream stream) {
		return new InternalAnnotationParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public AnnotationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AnnotationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
