/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.annot.desc.scoping;

import org.eclipse.xtext.xbase.annotations.typesystem.XbaseWithAnnotationsBatchScopeProvider;

public abstract class AbstractAnnotationScopeProvider extends XbaseWithAnnotationsBatchScopeProvider {
}
