/*
 * generated by Xtext 2.12.0
 */
package eu.jgen.notes.annot.desc.ide


/**
 * Use this class to register ide components.
 */
class AnnotationIdeModule extends AbstractAnnotationIdeModule {
}
